document.write('<table width="776" class="tableleftrightborder" height="43" border="0" align="center" cellpadding="0" cellspacing="0" background="/img10/index_line20_bg.gif">')
document.write('  <tr align="center"> ')
document.write('    <td>')
document.write('		<select name="Country" style="width:130px">')
document.write('		<option value="#">国家部委网站</option>')
document.write('		<option value="http://www.fmprc.gov.cn">外交部</option>')
document.write('		<option value="http://www.sdpc.gov.cn">国家发展和改革委员会</option>')
document.write('		<option value="http://www.moe.edu.cn">教育部</option>')
document.write('		<option value="http://www.most.gov.cn">科技部</option>')
document.write('		<option value="http://www.costind.gov.cn">国防科工委</option>')
document.write('		<option value="http://www.seac.gov.cn ">国家民委</option>')
document.write('		<option value="http://www.mps.gov.cn">公安部</option>')
document.write('		<option value="http://www.mos.gov.cn/">监察部</option>')
document.write('		<option value="http://www.mca.gov.cn">民政部</option>')
document.write('		<option value="http://www.legalinfo.gov.cn/">司法部</option>')
document.write('		<option value="http://www.mof.gov.cn">财政部</option>')
document.write('		<option value="http://www.mop.gov.cn/">人事部</option>')
document.write('		<option value="http://www.molss.gov.cn">劳动和社会保障部</option>')
document.write('		<option value="http://www.mlr.gov.cn/index.jsp">国土资源部</option>')
document.write('		<option value="http://www.cin.gov.cn">建设部</option>')
document.write('		<option value="http://www.chinamor.cn.net">铁道部</option>')
document.write('		<option value="http://www.moc.gov.cn">交通部</option>')
document.write('		<option value="http://www.mii.gov.cn">信息产业部</option>')
document.write('		<option value="http://www.wwr.gov.cn/">水利部</option>')
document.write('		<option value="http://www.agri.gov.cn">农业部</option>')
document.write('		<option value="http://www.mofcom.gov.cn">商务部</option>')
document.write('		<option value="http://www.ccnt.gov.cn">文化部</option>')
document.write('		<option value="http://www.moh.gov.cn">卫生部</option>')
document.write('		<option value="http://www.sfpc.gov.cn">国家人口与计生委</option>')
document.write('		<option value="http://www.pbc.gov.cn/">中国人民银行</option> ')
document.write('		<option value="http://www.audit.gov.cn/">审计署</option> ')
document.write('		<option value="http://www.cma.gov.cn">中国气象局</option>')
document.write('		<option value="http://www.sepa.gov.cn/">国家环境保护总局</option>')
document.write('		</select>')
document.write('		<script language=vbs>')
document.write('		sub Country_onchange()')
document.write('			if Country.value<>"#" then')
document.write('				window.open Country.value,""')
document.write('			end if')
document.write('		end sub')
document.write('		</script>')
document.write('        </td>')
document.write('        <td> ')
document.write('		<select name="state" style="width:130px">')
document.write('		<option value="#">省(区市)政府网站</option>')
document.write('		<option value="http://www.tj.gov.cn">天津</option>')
document.write('		<option value="http://www.hebei.gov.cn">河北</option>')
document.write('		<option value="http://www.sd.gov.cn/">山东</option>')
document.write('		<option value="http://www.sxpublic.gov.cn">山西</option>')
document.write('		<option value="http://www.nmg.gov.cn">内蒙古</option>')
document.write('		<option value="http://www.ln.gov.cn ">辽宁</option>')
document.write('		<option value="http://www.jl.gov.cn">吉林</option>')
document.write('		<option value="http://www.hlj.gov.cn">黑龙江</option>')
document.write('		<option value="http://www.shanghai.gov.cn">上海</option>')
document.write('		<option value="http://www.zhejiang.gov.cn">浙江</option>')
document.write('		<option value="http://www.ah.gov.cn">安徽</option>')
document.write('		<option value="http://www.fujian.gov.cn">福建</option>')
document.write('		<option value="http://www.jiangxi.gov.cn ">江西</option>')
document.write('		<option value="http://www.henan.gov.cn">河南</option>')
document.write('		<option value="http://www.hubei.gov.cn">湖北</option>')
document.write('		<option value="http://www.hunan.gov.cn">湖南</option>')
document.write('		<option value="http://www.gd.gov.cn">广东</option>')
document.write('		<option value="http://www.gxi.gov.cn">广西</option>')
document.write('		<option value="http://www.hainan.gov.cn">海南</option>')
document.write('		<option value="http://www.cq.gov.cn">重庆</option>')
document.write('		<option value="http://www.sc.gov.cn">四川</option>')
document.write('		<option value="http://www.gzgov.gov.cn">贵州</option>')
document.write('		<option value="http://www.yn.gov.cn">云南</option>')
document.write('		<option value="http://www.gansu.gov.cn">甘肃</option>')
document.write('		<option value="http://www.qh.gov.cn">青海</option>')
document.write('		<option value="http://www.info.gov.hk">香港</option>')
document.write('		<option value="http://www.macau.gov.mo">澳门</option> ')
document.write('		</select>')
document.write('		<script language=vbs>')
document.write('		sub state_onchange()')
document.write('			if state.value<>"#" then')
document.write('				window.open state.value,""')
document.write('			end if')
document.write('		end sub')
document.write('		</script>')
document.write('        </td>')
document.write('        <td> ')
document.write('		<select name="beijing" style="width:130px">')
document.write('		<option value="#">首都网站群</option>')
document.write('		<option value="http://www.bjrd.gov.cn/">市人大常委会</option>')
document.write('		<option value="http://www.bjzx.gov.cn/">市政协</option>')
document.write('		<option value="http://www.bjgf.gov.cn/">市高级人民法院</option>')
document.write('		<option value="http://www.bjjc.gov.cn/">市人民检察院</option>')
document.write('		<option value="http://www.bjgov.gov.cn">市政府办公厅</option>')
document.write('		<option value="http://www.bjpc.gov.cn/">市发展计划委员会</option>')
document.write('		<option value="http://www.bjec.gov.cn/">市经济委员会</option>')
document.write('		<option value="http://www.bjsw.gov.cn/">市商业委员会</option>')
document.write('		<option value="http://www.bjedu.gov.cn/">市教育委员会</option>')
document.write('		<option value="http://www.bestinfo.net.cn/">市科学技术委员会</option>')
document.write('		<option value="http://www.bjethnic.gov.cn/">市民族事务委员会</option>')
document.write('		<option value="http://www.bjgaj.gov.cn/">市公安局</option>')
document.write('		<option value="http://www.bjsupervision.gov.cn/">市监察局</option>')
document.write('		<option value="http://www.bjmzj.gov.cn/">市民政局</option>')
document.write('		<option value="http://www.bjsf.gov.cn/">市司法局</option>')
document.write('		<option value="http://www.bjcz.gov.cn/">市财政局</option>')
document.write('		<option value="http://www.bjp.gov.cn/">市人事局</option>')
document.write('		<option value="http://www.bjldbzj.gov.cn/">市劳动和社会保障局</option>')
document.write('		<option value="http://www.bjghw.gov.cn/">市规划委员会</option>')
document.write('		<option value="http://www.bjjs.gov.cn/">市建设委员会</option>')
document.write('		<option value="http://www.bjmac.gov.cn/">市政管理委员会</option>')
document.write('		<option value="http://www.bjgtfgj.gov.cn/">市国土资源局</option>')
document.write('		<option value="http://www.bjtb.gov.cn/">市交通委员会</option>')
document.write('		<option value="http://www.bjnw.gov.cn/">市农村工作委员会</option>')
document.write('		<option value="http://www.bjfetc.gov.cn/">市对外经济贸易委员会</option>')
document.write('		<option value="http://www.bcbnet.org/">市文化局</option>')
document.write('		<option value="http://www.bjhb.gov.cn/">市卫生局</option>')
document.write('		<option value="http://www.bjfc.gov.cn/">市计划生育委员会</option>')
document.write('		<option value="http://www.bjab.gov.cn/">市审计局</option>')
document.write('		<option value="http://www.bjshjs.gov.cn/">市社会建设工作办公室</option>')
document.write('		<option value="http://www.tax861.gov.cn/">市地方税务局 </option>')
document.write('		<option value="http://www.bjepb.gov.cn/">市环境保护局</option>')
document.write('		<option value="http://www.bjstats.gov.cn/">市统计局</option>')
document.write('		<option value="http://www.hd315.gov.cn/">市工商行政管理局</option>')
document.write('		<option value="http://www.bjtsb.gov.cn/">市质量技术监督局</option>')
document.write('		<option value="http://www.bjda.gov.cn/">市药品监督管理局</option>')
document.write('		<option value="http://www.bjwater.gov.cn/">市水利局</option>')
document.write('		<option value="http://www.bjagri.gov.cn/">市农业局</option>')
document.write('		<option value="http://www.bjrt.gov.cn/">市广播电视局</option>')
document.write('		<option value="http://www.bjppb.gov.cn/">市新闻出版局 </option>')
document.write('		<option value="http://www.bjww.gov.cn/">市文物局</option>')
document.write('		<option value="http://www.bjta.gov.cn/">市旅游局</option>')
document.write('		<option value="http://www.bjsports.gov.cn/">市体育局</option>')
document.write('		<option value="http://www.bjbpl.gov.cn/">市园林局</option>')
document.write('		<option value="http://www.bjfao.gov.cn/">市政府外事办公室</option>')
document.write('		<option value="http://www.bjqb.gov.cn/">市政府侨务办公室</option>')
document.write('		<option value="http://www.bjfzb.gov.cn/">市政府法制办公室</option>')
document.write('		<option value="http://www.bjtgb.gov.cn/">市经济体制改革办公室</option>')
document.write('		<option value="http://www.bjxfb.gov.cn/">市委市政府信访办公室</option>')
document.write('		<option value="http://www.bjyjs.gov.cn/">市政府研究室</option>')
document.write('		<option value="http://www.bjwj.gov.cn/">市物价局</option>')
document.write('		<option value="http://www.bte.gov.cn/">市乡镇企业局</option>')
document.write('		<option value="http://www.bjjgj.gov.cn/">市监狱管理局</option>')
document.write('		<option value="http://www.bjlsj.gov.cn/">市粮食局</option>')
document.write('		<option value="http://www.bjtcm.gov.cn/">市中医管理局</option>')
document.write('		<option value="http://www.bjrf.gov.cn/">市人民防空办公室</option>')
document.write('		<option value="http://www.greenbeijing.gov.cn/">首都绿化委员会办公室(市林业局)</option>')
document.write('		<option value="http://www.bnii.gov.cn/">市信息化工作办公室</option>')
document.write('		<option value="http://www.bjsupervision.gov.cn/">市纪律检查委员会机关</option>')
document.write('		<option value="http://www.bjdj.gov.cn/">市委组织部（北京党建）</option>')
document.write('		<option value="http://www.beijing.org.cn/">市对外宣传领导小组办公室（新闻办）</option>')
document.write('		<option value="http://www.bjstb.gov.cn/">市委台湾工作办公室 </option>')
document.write('		<option value="http://www.bjbb.gov.cn/">市机构编制委员会办公室</option>')
document.write('		<option value="http://www.bjwmb.gov.cn/">首都精神文明建设委员会办公室（首都文明热线）</option>')
document.write('		<option value="http://www.bjbmj.gov.cn/">市国家保密局</option>')
document.write('		<option value="http://www.bjgygw.gov.cn/">市工业党建网</option>')
document.write('		<option value="http://www.bjjtgl.gov.cn/">市公安局公安交通管理局</option>')
document.write('		<option value="http://www.bjcab.gov.cn/">市版权局</option>')
document.write('		<option value="http://www.bjkab.gov.cn/">市政府口岸办公室</option>')
document.write('		<option value="http://www.bjcss.gov.cn/">市政府参事室</option>')
document.write('		<option value="http://www.bjdkj.gov.cn/">市地质矿产勘查开发局</option>')
document.write('		<option value="http://www.bjma.gov.cn/">市档案局</option>')
document.write('		<option value="http://www.bjxfj.gov.cn/">市消防局</option>')
document.write('		<option value="http://www.zgc.gov.cn/">中关村科技园区管理委员会</option>')
document.write('		<option value="http://www.bjstb.gov.cn/">市政府台湾事务办公室</option>')
document.write('		<option value="http://www.bj-procurement.gov.cn/">市政府采购办公室</option>')
document.write('		<option value="http://www.bjcustoms.gov.cn/">中华人民共和国北京海关</option>')
document.write('		<option value="http://www.bjciq.gov.cn/">北京出入境检验检疫局</option>')
document.write('		<option value="http://www.bjcg.gov.cn/">市城市管理综合行政执法局</option>')
document.write('		<option value="http://www.bjsat.gov.cn/">市国家税务局</option>')
document.write('		<option value="http://www.bjaw.org.cn/">市爱国卫生运动委员会</option>')
document.write('		<option value="http://www.bjdch.gov.cn/">东城区</option>')
document.write('		<option value="http://www.bjxch.gov.cn/">西城区</option>')
document.write('		<option value="http://www.bjchw.gov.cn/">崇文区</option>')
document.write('		<option value="http://www.bjxw.gov.cn/">宣武区</option>')
document.write('		<option value="http://www.bjchy.gov.cn/">朝阳区</option>')
document.write('		<option value="http://www.bjhd.gov.cn/">海淀区</option>')
document.write('		<option value="http://www.bjft.gov.cn/">丰台区</option>')
document.write('		<option value="http://www.bjsjs.gov.cn/">石景山区</option>')
document.write('		<option value="http://www.bjshy.gov.cn/">顺义区</option>')
document.write('		<option value="http://www.bjchp.gov.cn/">昌平区</option>')
document.write('		<option value="http://www.bjmtg.gov.cn/">门头沟区</option>')
document.write('		<option value="http://www.bjtzh.gov.cn/">通州区</option>')
document.write('		<option value="http://www.bjfsh.gov.cn/">房山区</option>')
document.write('		<option value="http://www.bjdx.gov.cn/">大兴区</option>')
document.write('		<option value="http://www.bjyq.gov.cn/">延庆县</option>')
document.write('		<option value="http://www.bjhr.gov.cn/">怀柔区</option>')
document.write('		<option value="http://www.bjpg.gov.cn/">平谷区</option>')
document.write('		<option value="http://www.bjmy.gov.cn/">密云县</option>')
document.write('		<option value="http://www.bjzgh.gov.cn/">市总工会</option>')
document.write('		<option value="http://www.bjwomen.gov.cn/">市妇联</option>')
document.write('		<option value="http://www.bast.cn.net/">市科学技术协会（科普之窗）</option>')
document.write('		<option value="http://www.greenbeijing.org/">北京绿化基金会</option>')
document.write('		<option value="http://www.bjql.org.cn/">市归国华侨联合会</option>')
document.write('		<option value="http://www.bdpf.org.cn/">市残疾人联合会</option>')
document.write('		<option value="http://www.bjofa.org.cn/">北京海外联谊会</option>')
document.write('		<option value="http://www.bjmb.gov.cn/">市气象局</option>')
document.write('		<option value="http://www.bjpta.gov.cn/">市人事考试中心</option>')
document.write('		<option value="http://www.bac.gov.cn/">市委党校</option>')
document.write('		</select>')
document.write('		<script language=vbs>')
document.write('		sub beijing_onchange()')
document.write('			if beijing.value<>"#" then')
document.write('				window.open beijing.value,""')
document.write('			end if')
document.write('		end sub')
document.write('		</script>')
document.write('        </td>')
document.write('        <td> ')
document.write('		<select name="Academy" style="width:130px">')
document.write('		<option value="#">首都高校网站</option>')
document.write('		<option value="http://www.pku.edu.cn">北京大学</option>')
document.write('		<option value="http://www.tsinghua.edu.cn">清华大学</option>')
document.write('		<option value="http://www.ruc.edu.cn">中国人民大学</option>')
document.write('		<option value="http://www.njtu.edu.cn">北方交通大学</option>')
document.write('		<option value="http://www.bjpu.edu.cn">北京工业大学</option>')
document.write('		<option value="http://www.buaa.edu.cn">北京航空航天大学</option>')
document.write('		<option value="http://www.bit.edu.cn">北京理工大学</option>')
document.write('		<option value="http://www.bupt.edu.cn">北京邮电大学</option>')
document.write('		<option value="http://www.cufe.edu.cn">中央财经大学</option>')
document.write('		<option value="http://www.bnu.edu.cn">北京师范大学</option>')
document.write('		<option value="http://www.bjaeu.edu.cn">中国农业大学</option>')
document.write('		<option value="http://www.bjfu.edu.cn">北京林业大学</option>')
document.write('		<option value="http://www.ustb.edu.cn">北京科技大学</option>')
document.write('		<option value="http://www.imicams.ac.cn">中国协和医科大学</option>')
document.write('		<option value="http://www.ncut.edu.cn">北方工业大学</option>')
document.write('		<option value="http://www.buct.edu.cn">北京化工大学</option>')
document.write('		<option value="http://www.btbu.edu.cn">北京工商大学</option>')
document.write('		<option value="http://www.bigc.edu.cn">北京印刷学院</option>')
document.write('		<option value="http://www.bicea.net.cn">北京建筑工程学院</option>')
document.write('		<option value="http://www.bipt.edu.cn">北京石油化工学院</option>')
document.write('		<option value="http://www.cpums.edu.cn">首都医科大学</option>')
document.write('		<option value="http://www.bjucmp.edu.cn">北京中医药大学</option>')
document.write('		<option value="http://www.cnu.edu.cn">首都师范大学</option>')
document.write('		<option value="http://www.bfsu.edu.cn">北京外国语大学</option>')
document.write('		<option value="http://www.erwai.net">北京第二外国语学院</option>')
document.write('		<option value="http://www.blcu.edu.cn">北京语言文化大学</option>')
document.write('		<option value="http://www.bbi.edu.cn">中国传媒大学</option>')
document.write('		<option value="http://www.uibe.edu.cn">对外经济贸易大学</option>')
document.write('		<option value="http://www.fac.edu.cn">外交学院</option>')
document.write('		<option value="http://www.cppsu.edu.cn">中国人民公安大学</option>')
document.write('		<option value="http://www.uir.edu.cn">国际关系学院</option>')
document.write('		<option value="http://www.bupe.edu.cn">北京体育大学</option>')
document.write('		<option value="http://www.ccom.edu.cn">中央音乐学院</option>')
document.write('		<option value="http://www.bfa.edu.cn">北京电影学院</option>')
document.write('		<option value="http://www.bjdance.com">北京舞蹈学院</option>')
document.write('		<option value="http://www.cun.edu.cn">中央民族大学</option>')
document.write('		<option value="http://www.cupl.edu.cn">中国政法大学</option>')
document.write('		<option value="http://www.biti.edu.cn">北京信息工程学院</option>')
document.write('		<option value="http://www.buu.edu.cn">北京联合大学</option>')
document.write('		<option value="http://www.cyu.edu.cn">中国青年政治学院</option>')
document.write('		<option value="http://www.cueb.edu.cn/">首都经济贸易大学</option>')
document.write('		<option value="http://www.bmi.edu.cn">北京物资学院</option>')
document.write('		</select>')
document.write('		<script language=vbs>')
document.write('		sub academy_onchange()')
document.write('			if academy.value<>"#" then')
document.write('				window.open academy.value,""')
document.write('			end if')
document.write('		end sub')
document.write('		</script>')
document.write('        </td>')
document.write('        <td> ')
document.write('		<select name="Media">')
document.write('		<option>新闻媒体网站</option>')
document.write('		<option value="http://www.xinhuanet.com">新华网</option>')
document.write('		<option value="http://www.people.com.cn">人民网</option>')
document.write('		<option value="http://www.cycnet.com">中青网</option>')
document.write('		<option value="http://www.cctv.com">央视国际</option>')
document.write('		<option value="http://www.cnradio.com">中央人民广播电台</option>')
document.write('		<option value="http://www.cri.com.cn">中国国际广播电台</option>')
document.write('		<option value="http://www.gmw.cn">光明网</option>')
document.write('		<option value="http://www.economicdaily.com.cn">经济日报</option>')
document.write('		<option value="http://www.chinadaily.com.cn">中国日报</option>')
document.write('		<option value="http://www.chinanews.com.cn">中国新闻社</option>')
document.write('		<option value="http://www.bjd.com.cn">京报网</option>')
document.write('		<option value="http://www.btv.com.cn">北京电视台</option>')
document.write('		<option value="http://www.bjradio.com.cn/">北京人民广播电台</option>')
document.write('		<option value="http://www.beijingnews.com.cn">千龙新闻网</option>')
document.write('		<option value="http://www.ynet.com">北京青年报</option>')
document.write('		<option value="http://www.morningpost.com.cn/">北京晨报</option> ')
document.write('		<option value="http://www.sina.com.cn">新浪</option> ')
document.write('		<option value="http://www.sohu.com">搜狐</option>')
document.write('		<option value="http://www.china.com.cn/chinese/index.htm">中国网</option>')
document.write('		<option value="http://www.ce.cn/">中国经济网</option>')
document.write('		<option value="http://www.cyol.net/">中青在线</option>')
document.write('		<option value="http://www.eastday.com/">东方网</option>')
document.write('		<option value="http://www.enorth.com.cn/">北方网</option>')
document.write('		<option value="http://www.southcn.com/">南方网</option>')
document.write('		<option value="http://www.nanfangdaily.com.cn/southnews/">南方报业网</option>')
document.write('		<option value="http://www.nanfangdaily.com.cn/southnews/">大洋网</option>')
document.write('		<option value="http://www.bjt.net.cn/">京华时报</option>')
document.write('		<option value="http://www.163.com/">网易</option>')
document.write('		<option value="http://www.tom.com/">TOM</option>')
document.write('		<option value="http://cn.yahoo.com/">雅虎中国</option>')
document.write('		</select>')
document.write('		<script language=vbs>')
document.write('		sub Media_onchange()')
document.write('			if Media.value<>"#" then')
document.write('				window.open Media.value,""')
document.write('			end if')
document.write('		end sub')
document.write('		</script>')
document.write('    </td>')
document.write('  </tr>')
document.write('</table>')